apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: pgbouncer
spec:
  type: ClusterIP
  selector:
    app: {{ template "patroni.fullname" . }}
    release: {{ .Release.Name }}-pgbouncer
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "patroni.fullname" . }}-pgbouncer
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}-pgbouncer
    heritage: {{ .Release.Service }}
    component: pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "patroni.fullname" $ }}
      release: {{ .Release.Name }}-pgbouncer
      component: pgbouncer
  template:
    metadata:
      labels:
        app: {{ template "patroni.fullname" . }}
        release: {{ .Release.Name }}-pgbouncer
        component: pgbouncer
    spec:
      serviceAccountName: {{ template "patroni.serviceAccountName" . }}
      containers:
      - name: pgbouncer
        image: "{{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}"
        imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-xec"
            - |
              /usr/bin/pg_isready -h {{ template "patroni.hashedname" . }} -p 5432 -U {{ .Values.pgbouncer.credentials.username }} -d postgres
              /usr/bin/pg_isready -h 127.0.0.1 -p 5432 -U {{ .Values.pgbouncer.credentials.username }} -d postgres
        volumeMounts:
        - name: pgbouncer-userlist
          mountPath: /etc/pgbouncer
          readOnly: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
    {{- end }}
      volumes:
      - name: pgbouncer-userlist
        secret:
          secretName: {{ template "patroni.fullname" . }}-pgbouncer
          defaultMode: 0555
          optional: false
