apiVersion: v1
kind: Secret
metadata:
  name: {{ template "patroni.fullname" . }}-pgbouncer
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  pgbouncer.ini: {{ include "patroni.pgbouncer" . | b64enc }}
  userlist.txt: {{ printf "\"%s\" \"%s\"" .Values.pgbouncer.credentials.username .Values.pgbouncer.credentials.password | b64enc }}
