apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: access
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  - name: patroni
    port: 8008
    targetPort: patroni
    protocol: TCP
---
# headless service to manage Endpoints object whose annotations serve as cluster state
apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}-config
  labels:
    app: {{ template "patroni.fullname" . }}
    chart: {{ template "patroni.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: cluster-state-lock
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: patroni
    port: 8008
    targetPort: patroni
    protocol: TCP
