{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-config
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent-bit-service.conf: |-
    [SERVICE]
        Flush        {{ .Values.service.flush }}
        Daemon       Off
        Log_Level    {{ .Values.service.logLevel }}
        Parsers_File parsers.conf
{{- if .Values.parsers.enabled }}
        Parsers_File parsers_custom.conf
{{- end }}
{{- if .Values.metrics.enabled }}
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
{{- end }}

  fluent-bit-input.conf: |-
    [INPUT]
        Name             tail
        Path             {{ .Values.input.tail.path }}
        Parser           {{ .Values.input.tail.parser }}
        Tag              {{ .Values.filter.kubeTag }}.*
        Refresh_Interval 5
        Mem_Buf_Limit    {{ .Values.input.tail.memBufLimit }}
        Skip_Long_Lines  On
{{- if .Values.trackOffsets }}
        DB               /tail-db/tail-containers-state.db
        DB.Sync          Normal
{{- end }}
{{- if .Values.input.systemd.enabled }}
    [INPUT]
        Name            systemd
        Tag             {{ .Values.input.systemd.tag }}
{{- range $value := .Values.input.systemd.filters.systemdUnit }}
        Systemd_Filter  _SYSTEMD_UNIT={{ $value }}
{{- end }}
        Max_Entries     {{ .Values.input.systemd.maxEntries }}
        Read_From_Tail  {{ .Values.input.systemd.readFromTail }}
{{- end }}
{{ .Values.extraEntries.input | indent 8 }}

  fluent-bit-filter.conf: |-
    [FILTER]
        Name                kubernetes
        Match               {{ .Values.filter.kubeTag }}.*
        Kube_Tag_Prefix     {{ .Values.filter.kubeTagPrefix }}
        Kube_URL            {{ .Values.filter.kubeURL }}
        Kube_CA_File        {{ .Values.filter.kubeCAFile }}
        Kube_Token_File     {{ .Values.filter.kubeTokenFile }}
{{- if .Values.filter.mergeJSONLog }}
        Merge_Log           On
{{- end }}

{{- if .Values.filter.mergeLogKey }}
        Merge_Log_Key       {{ .Values.filter.mergeLogKey }}
{{- end }}

{{- if .Values.filter.enableParser }}
        K8S-Logging.Parser  On
{{- end }}
{{- if .Values.filter.enableExclude }}
        K8S-Logging.Exclude On
{{- end }}
{{ .Values.extraEntries.filter | indent 8 }}

  fluent-bit-output.conf: |-
{{- range .Values.outputs }}
    [OUTPUT]
        Name {{ .type }}
        Match {{ .match | default "*" }}
{{- if eq .type "test" }}
        Path {{ .path | default "/tmp/fluent-bit.log" }}
{{- else if eq .type "forward" }}
        Host          {{ .host }}
        Port          {{ .port }}
        Retry_Limit False
{{- if .shared_key }}
        Shared_Key    {{ .shared_key }}
{{- end }}
{{- else if eq .type "es" }}
        Host  {{ .host }}
        Port  {{ .port }}
        Logstash_Format {{ default "On" .logstash_format  }}
        Retry_Limit False
        Type  {{ .type }}
{{- if .time_key }}
        Time_Key {{ .time_key }}
{{- end }}
{{- if .replace_dots }}
        Replace_Dots {{ .replace_dots }}
{{- end }}
{{- if .logstash_prefix }}
        Logstash_Prefix {{ .logstash_prefix }}
{{ else if .index }}
        Index {{ .index }}
{{- end }}
{{- if .http_user }}
        HTTP_User {{ .http_user }}
{{- if .http_passwd }}
        HTTP_Passwd {{ .http_passwd }}
{{- else }}
        HTTP_Passwd ${HTTP_PASSWORD}
{{- end }}
{{- end }}
{{ if eq .tls "on" }}
        tls {{ .tls }}
        tls.verify {{ .tls_verify }}
        tls.debug {{ .tls_debug }}
{{- if .tls_ca }}
        tls.ca_file /secure/es-tls-ca.crt
{{- end }}
{{- end }}
{{- else if eq .type "splunk" }}
        Host  {{ .host }}
        Port  {{ .port }}
        Splunk_Token  {{ .token }}
        Splunk_Send_Raw {{ .send_raw }}
        TLS   {{ .tls }}
        TLS.Verify   {{ .tls_verify }}
        tls.debug {{ .tls_debug }}
        Message_Key   {{ .message_key }}
{{- else if eq .type "http" }}
        Host {{ .host }}
        Port {{ .port }}
        URI {{ .uri }}
{{- if .http_user }}
        HTTP_User {{ .http_user }}
        HTTP_Passwd {{ .http_passwd }}
{{- end }}
        tls {{ .tls }}
        tls.verify {{ .tls_verify }}
        tls.debug {{ .tls_debug }}
{{- if .proxy }}
        Proxy {{ .proxy }}
{{- end }}
        Format {{ .format }}
{{ end }}
{{- range .headers }}
        Header  {{ . }}
{{- end }}
{{ .extraEntries | default "" | indent 8 }}
{{- end }}

  fluent-bit.conf: |-
{{ .Values.rawConfig | indent 4 }}

  parsers.conf: |-
{{- if .Values.parsers.regex }}
{{- range .Values.parsers.regex }}
    [PARSER]
        Name        {{ .name }}
        Format      regex
        Regex       {{ .regex }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.json }}
{{- range .Values.parsers.json }}
    [PARSER]
        Name        {{ .name }}
        Format      json
{{- if .timeKeep }}
        Time_Keep   {{ .timeKeep }}
{{- end }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .decodeFieldAs  }}
        Decode_Field_As {{ .decodeFieldAs }} {{ .decodeField | default "log" }}
{{- end}}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.logfmt }}
{{- range .Values.parsers.logfmt }}
    [PARSER]
        Name        {{ .name }}
        Format      logfmt
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}

{{- end -}}
