{{- if .Values.kafkaTrigger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-trigger-controller
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels.standard" . | indent 4 }}
    kubeless: kafka-trigger-controller
spec:
  selector:
    matchLabels:
      kubeless: kafka-trigger-controller
  template:
    metadata:
      labels:
        kubeless: kafka-trigger-controller
        app: {{ template "kubeless.name"  . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - image: "{{ .Values.kafkaTrigger.deployment.image.repository }}:{{ .Values.kafkaTrigger.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.kafkaTrigger.deployment.image.pullPolicy }}
        name: kafka-trigger-controller
        env:
        - name: KAFKA_BROKERS
          value: {{ .Values.kafkaTrigger.env.kafkaBrokers }}
      serviceAccountName: controller-acct
{{- end }}
